#include <iostream>
#include <vector>
#include <string>
#include <map>
#include <fstream>
#include <unordered_map>
#include <ctype.h>
#include <algorithm>
#include <stdio.h>
#include <chrono>
#include <iomanip>
#include "aho.hpp"
#include <iomanip>